### ISSUE TITLE
Dataset used to run the project

### ISSUE THREAD

**Issue by nannuarun** [BNN-UPC/RouteNet-Fermi#1]
Hi Team,

Can you help me with the dataset needed to run the project. We don't have the dataset in the github.

Thanks,
Arun Kumar.

**Comment by MiquelFerriol** [comment]
Dear @nannuarun,
You can find all the datasets used in the experiment [here](https://github.com/BNN-UPC/NetworkModelingDatasets/tree/master/datasets_v6).

Also, we updated the readme files in each experiment directory with some instructions to download and reproduce the experiment.

If you have any more questions, do not hesitate to ask.

Bests,
Miquel
