### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by tonid7** [BNN-UPC/RouteNet-Fermi#2]
Hi,

Seems all the READMEs refer to install reqs from the subject file but its missing from the repo. Is it possible to add one (or perhaps multiple if needed)?

Thanks!

Best Regards,
Toni

**Comment by MiquelFerriol** [comment]
Dear @tonid7,
Thank you for pointing this out. We updated the repository to include the [requierements.txt](https://github.com/BNN-UPC/RouteNet-Fermi/blob/main/requirements.txt) file.

Thanks,
Miquel
